name: build artifacts
on:
  push:
    tags:
      - "*_v[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          ./getDependencies.sh &&
          ./cloneRepos.sh &&
          ./applyFixesAndOverride.sh

      - name: Build Hetuw artifacts
        run: |
          yes | ./repo/changeWhatToBuild.sh tholHetuw
          ./compile.sh 1 &&
          ./cleanOldBuildsAndOptionallyCaches.sh 1

          yes | ./repo/changeWhatToBuild.sh townplanner
          ./editor.sh 1 &&
          ./cleanOldBuildsAndOptionallyCaches.sh 1

          mkdir ../bin

          mv ../output/OneLife ../output/Hetuw_with_minitech_Linux
          mv ../output/EditOneLife ../output/TownPlanner_Linux

          cp -rL ../output ./2hol_ubuntu_20-04

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          body: |
            Hetuw modded 2hol distributions.
          files: |
            ../output/Hetuw_with_minitech_Linux
            ../output/TownPlanner_Linux
            ./2hol_ubuntu_20-04
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
