name: build artifacts
on:
  push:
    tags:
      - "*_v[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          ./getDependencies.sh &&
          ./cloneRepos.sh &&
          ./applyFixesAndOverride.sh

      - name: Build Hetuw artifacts
        run: |
          yes | ./repo/changeWhatToBuild.sh tholHetuw
          ./compile.sh 1 &&
          ./cleanOldBuildsAndOptionallyCaches.sh 1

          yes | ./repo/changeWhatToBuild.sh townplanner
          ./editor.sh 1 &&
          ./cleanOldBuildsAndOptionallyCaches.sh 1

          mkdir ../bin

          mv ../output/OneLife ./Hetuw_with_minitech_Linux
          mv ../output/EditOneLife ./TownPlanner_Linux

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            ./Hetuw_with_minitech_Linux
            ./TownPlanner_Linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
